### ISSUE TITLE
Fix physics of MouseAgent

### ISSUE THREAD

**Issue by mbuet2ner** [mbuet2ner/Unity3Dmice#12]
After a collision, the MouseAgent just falls off the map at some point (and also crosses the fences). There seems to be an issue with either the MouseAgent physics or the terrain physics (or both).

As a workaround we could just reset the MouseAgent if it leaves the area beyond the fences, but that does not really fix the problem.

**Comment by samiva** [comment]
What collision? Does it collide on a tree and then after sometime fall from the map?

**Comment by samiva** [comment]
Or do you mean it goes through fences and then after some time it falls?
