### ISSUE TITLE
MouseAgent not moving

### ISSUE THREAD

**Issue by mbuet2ner** [mbuet2ner/Unity3Dmice#5]
Currently the agent does not move when the training process starts. There has to be some small bug somewhere!

**Comment by samiva** [comment]
Do you use Unity while training? Does the Unity log show any errors?

**Comment by samiva** [comment]
Are you really sure about the vector action spacetype being discrete?

**Comment by mbuet2ner** [comment]
It does not show any errors. And I used Unity. It is a bug in the implementation and may be due to some components not wired properly together. It is only related to our code!

**Comment by mbuet2ner** [comment]
Fixed with e4c6e79a212f3a6951606cf97a5d0e680248d69a :tada:
