### ISSUE TITLE
Add border to the environment

### ISSUE THREAD

**Issue by mbuet2ner** [mbuet2ner/Unity3Dmice#7]
It would be great, if there was a border (e.g. rocks, river, hill...) that serves as a border of our environment, so that agents cannot fall down into nothingness...

**Comment by MattHaluska** [comment]
Hello I would like to contribute to this is issue. Is it possible ?

**Comment by mbuet2ner** [comment]
Hey @MattHaluska ! Glad that you take interest in our project. I am afraid, we cannot have other contributors as of now, since this is a university project...

But feel free to fork the project and work on it :+1: . Hope this helps!

**Comment by MattHaluska** [comment]
I understand. Thank you for your answer. Good luck with project 👍
